'use strict';

const TRIP_DATA = {
  meta: {
    title: "The Adventure of Sarah, Sepehr & Kye",
    subtitle: "West Coast Loop: Escondido to Seattle and Back",
    dates: "June 18 (evening) - July 5, 2026",
  },
  stats: [
    { value: "~3,600", label: "miles" },
    { value: "11", label: "camp nights" },
    { value: "3", label: "motel nights" },
    { value: "3", label: "Seattle Airbnb nights" },
    { value: "1 dog", label: "Kye on tour" },
  ],
  warnings: [
    { icon: "🐕", title: "Trail Restrictions", sev: "high", desc: "Dogs are banned from dirt trails in nearly all CA State Parks and National Parks. Use campgrounds, paved paths, roads, National Forests, Oregon, and beaches for real dog time." },
    { icon: "🌾", title: "Foxtails", sev: "high", desc: "Barbed seeds can burrow into paws, ears, and noses. Check Kye's paws between toes and ears every night with a headlamp; pack tweezers." },
    { icon: "🐍", title: "Rattlesnakes", sev: "high", desc: "Peak risk in Columbia Gorge, Smith Rock, and the Eastern Sierra floor. Keep Kye on a strict 6-foot leash with no retractable leash." },
    { icon: "🐻", title: "Bear Country", sev: "high", desc: "Redwoods, Lassen NF, and the Eastern Sierra require bear discipline. Dog food goes in bear lockers or approved storage, never in the tent." },
    { icon: "🪨", title: "Volcanic Terrain", sev: "medium", desc: "Bend, Crater Lake, and Lassen areas can have sharp pumice. Dog booties such as Ruffwear Grip Trex are strongly recommended." },
    { icon: "🌡", title: "Heat + Tent", sev: "high", desc: "Remove the rainfly on hot days. Bring a cooling vest, Aluminet shade cloth, and extra water." },
    { icon: "🔥", title: "Wildfire Checks", sev: "high", desc: "Use Watch Duty every morning for real-time wildfire tracking and route decisions." },
    { icon: "💧", title: "Remote Water", sev: "medium", desc: "Carry 3 extra gallons of water in the trunk. Shasta, Lassen, and Highway 395 stretches are remote." },
    { icon: "🛣", title: "Big Sur Hwy 1", sev: "high", desc: "Hwy 1 reopened in Jan 2026 but remains slide-prone. Check Caltrans QuickMap the morning of the drive. Backup is US-101 via Paso Robles and Salinas." },
    { icon: "🏕", title: "Camping Availability", sev: "high", desc: "Summer coastal CA/OR camps sell out months ahead. Set Campflare or Campnab alerts now and book Hipcamp private backups." },
    { icon: "🎆", title: "July 3-4", sev: "high", desc: "No low-demand FCFS Sierra camping on July 4 weekend. Book reservable sites now and download iOverlander and Campendium for dispersed backups." },
  ],
  days: [
    {
      id: 0, label: "Night 0", date: "Thu, Jun 18",
      from: "Escondido, CA", to: "Ventura, CA",
      driveTime: "2.75-3.5h", miles: "~150 mi", zone: "coastal",
      lodgingType: "motel", lodgingName: "Motel 6 Ventura, CA - Beach",
      lodgingCost: "~$75-90", lodgingNotes: "1.5 blocks from beach. Free wifi, pool, free parking, dogs free. Book through motel6.com.",
      lodgingBackup: "Nearby cheap Ventura motel if Motel 6 fills.",
      route: "Evening freeway push past LA traffic",
      routeNotes: "Depart around 7-8 PM, arrive around 10 PM, sleep.",
      description: "Leave Thursday evening and skip LA traffic entirely. This is just the clean launch pad for the coast route.",
      stops: ["No sightseeing required; the win is getting north of Los Angeles."],
      activities: ["Arrive, quick Kye walk, sleep."],
      food: [],
      dogNotes: ["Dogs free at Motel 6.", "Keep the arrival routine simple so Kye settles quickly."],
      warnings: [],
    },
    {
      id: 1, label: "Day 1", date: "Fri, Jun 19",
      from: "Ventura, CA", to: "Morro Bay, CA",
      driveTime: "2.5-3h", miles: "~150 mi", zone: "coastal",
      lodgingType: "camp", lodgingName: "Morro Bay SP - Upper Section, Site 123",
      lodgingCost: "$43.25 paid", lodgingNotes: "BOOKED. Stay Fri 06/19/2026 2:00 PM to Sat 06/20/2026 12:00 PM. Upper Section sites 86-140, campsite 123. Confirmation #29558779. Purchased 06/03/2026. Regular campsite, active reservation; $35 campsite + $8.25 reservation fee.",
      lodgingBackup: "No backup needed for Jun 19 unless the reservation changes.",
      route: "US-101 N → CA-1 / Morro Bay",
      routeNotes: "Sarah works from motel wifi until late-morning checkout, then you head north with no rush.",
      description: "A gentle first coast day after Sarah's work morning. The first camp night is now locked at Morro Bay, which makes the next morning's Big Sur launch easy.",
      stops: ["Fiscalini Ranch Preserve in Cambria: free, dog-friendly ocean boardwalks.", "Optional Pismo detour for pier walk or Splash Cafe if timing feels easy.", "Morro Rock / Embarcadero evening walk."],
      activities: ["Check into Morro Bay SP after 2 PM.", "Morro Bay waterfront sunset walk with leashed Kye.", "Keep the first camp setup simple and organized."],
      food: [{ name: "Splash Cafe", note: "Optional Pismo stop for clam chowder bread bowl." }],
      dogNotes: ["Morro Bay SP campground allows dogs on leash.", "Use Morro Bay waterfront and developed paths for Kye; avoid signed wildlife-sensitive areas."],
      warnings: ["Reservation is active; bring confirmation #29558779."],
    },
    {
      id: 2, label: "Day 2", date: "Sat, Jun 20",
      from: "Morro Bay", to: "Monterey / Carmel",
      driveTime: "3.5-4.5h", miles: "~145 mi", zone: "coastal",
      lodgingType: "camp", lodgingName: "Veterans Memorial Park, Monterey",
      lodgingCost: "~$47", lodgingNotes: "In-town FCFS campground with hot showers and no electricity. No reservations. Go directly here on arrival and try for 2 nights.",
      lodgingBackup: "Laguna Seca Recreation Area; call 888-588-2267 and confirm no race or track event.",
      route: "CA-1 / Hwy 1 through Big Sur",
      routeNotes: "Break camp by the noon checkout, but still aim to leave early. Check Caltrans QuickMap for Hwy 1 status. Backup is US-101 via Paso Robles and Salinas.",
      description: "Big Sur is the drive: a dramatic 90-mile coastal stretch of Hwy 1. Monterey and Carmel are the destination.",
      stops: ["Garrapata State Park Gate 19: cliffside dirt trails, leashed dogs allowed.", "Rocky Creek Bridge north of Bixby: similar architecture, fewer crowds.", "Pfeiffer Beach: leashed dogs OK."],
      activities: ["Arrive Monterey by noon-1 PM when FCFS camps may open.", "If only one night is available at Veterans Memorial, take it and use Laguna Seca for the other night."],
      food: [],
      dogNotes: ["Garrapata Gate 19 is the Big Sur dog hike.", "Carmel Beach is a short drive once camp is secured."],
      warnings: ["Hwy 1 is slide-prone; check Caltrans QuickMap that morning."],
    },
    {
      id: 3, label: "Day 3", date: "Sun, Jun 21",
      from: "Monterey / Carmel", to: "Monterey / Carmel",
      driveTime: "Minimal", miles: "—", zone: "coastal",
      lodgingType: "camp", lodgingName: "Veterans Memorial Park or Laguna Seca",
      lodgingCost: "~$47+", lodgingNotes: "Second Monterey-area night from Day 2's campsite plan.",
      lodgingBackup: "Use Laguna Seca if Veterans Memorial only had one night.",
      route: "Local Monterey and Carmel hops",
      routeNotes: "Friends arrive; keep the car time minimal.",
      description: "Full day with friends in Monterey and Carmel, built around dog-friendly coastal time.",
      stops: ["Carmel Beach.", "Carmel village.", "Monterey Fisherman's Wharf."],
      activities: ["Carmel Beach is legally off-leash for dogs under voice control within 25 ft.", "Walk Carmel village patios and Monterey Fisherman's Wharf with Kye on leash."],
      food: [],
      dogNotes: ["Carmel Beach is a trip highlight for Kye.", "Use voice control and stay within the 25 ft rule."],
      warnings: [],
    },
    {
      id: 4, label: "Day 4", date: "Mon, Jun 22",
      from: "Monterey, CA", to: "San Jose, CA",
      driveTime: "2-3h", miles: "~75-120 mi", zone: "city",
      lodgingType: "motel", lodgingName: "Motel 6 San Jose, CA - South",
      lodgingCost: "~$84-97", lodgingNotes: "2 pets up to 150 lbs. $0 pet fee. Book through motel6.com.",
      lodgingBackup: "Nearby San Jose motel if needed.",
      route: "Monterey brunch → 17-Mile Drive → Santa Cruz → optional Half Moon Bay → San Jose",
      routeNotes: "This is the friends' plan day.",
      description: "A friend-plan transition day from Monterey into the Bay Area.",
      stops: ["Morning brunch in Monterey.", "17-Mile Drive with dogs in the car.", "Santa Cruz.", "Optional Half Moon Bay."],
      activities: ["Keep the day flexible and social."],
      food: [],
      dogNotes: ["17-Mile Drive is dog-friendly from the car and viewpoints.", "Motel 6 has no pet fee."],
      warnings: [],
    },
    {
      id: 5, label: "Day 5", date: "Tue, Jun 23",
      from: "San Jose, CA", to: "Van Damme SP / Mendocino, CA",
      driveTime: "5.5-6.5h", miles: "~200 mi", zone: "coastal",
      lodgingType: "camp", lodgingName: "Van Damme SP - Upper Loop, Site 033",
      lodgingCost: "$53.25 paid", lodgingNotes: "BOOKED. Stay Tue 06/23/2026 2:00 PM to Wed 06/24/2026 12:00 PM. Upper Loop sites 31-74, campsite 033. Confirmation #29557920. Purchased 06/03/2026. Regular campsite, active reservation; $45 campsite + $8.25 reservation fee.",
      lodgingBackup: "No backup needed for Jun 23 unless the reservation changes.",
      route: "Golden Gate → Sonoma Coast → Mendocino headlands",
      routeNotes: "This is the longest friend-plan coast day.",
      description: "Bay Area to the Mendocino coast by way of the Golden Gate, Sonoma Coast, and a booked night at Van Damme State Park.",
      stops: ["Golden Gate walk: leashed dogs on pedestrian path.", "Sonoma Coast.", "Mendocino headlands."],
      activities: ["Check into Van Damme SP after 2 PM.", "Evening coastal walk if time allows."],
      food: [{ name: "Princess Seafood Market", note: "Fort Bragg crab rolls on the dock." }],
      dogNotes: ["Golden Gate pedestrian path allows leashed dogs.", "Van Damme campground allows leashed dogs; keep Kye out of restricted park trails.", "Watch foxtails along dry coastal edges."],
      warnings: ["Reservation is active; bring confirmation #29557920."],
    },
    {
      id: 6, label: "Day 6", date: "Wed, Jun 24",
      from: "Van Damme SP / Mendocino, CA", to: "Humboldt Redwoods, CA",
      driveTime: "3.5-4h", miles: "~155 mi", zone: "forest",
      lodgingType: "camp", lodgingName: "Burlington Campground, Humboldt Redwoods SP",
      lodgingCost: "~$35", lodgingNotes: "Right on Avenue of the Giants by the visitor center. 57 sites, dog-friendly on 6 ft leash, coin showers, flush toilets, bear boxes. Reserve via ReserveCalifornia.",
      lodgingBackup: "Hidden Springs Campground in the same park, seasonal and reservable.",
      route: "Hwy 1 south to US-101 north, then Avenue of the Giants",
      routeNotes: "From Van Damme, use the winding Mendocino-to-101 connector before heading north into the redwoods.",
      description: "This replaces the old 8-9 hour rush to Eugene. You get a real afternoon and evening in the redwoods.",
      stops: ["Avenue of the Giants: 32-mile scenic drive through old-growth.", "Rockefeller Forest via Mattole Road: walk leashed Kye along the county road shoulder under huge canopies.", "Eel River gravel bars by Burlington Campground."],
      activities: ["Drive slowly and pull over at every grove.", "Let Kye swim and fetch in the slow, shallow South Fork Eel River if conditions are safe.", "Evening grove pullouts for redwood light."],
      food: [{ name: "Eel River Brewing", note: "Fortuna; massive dog patio." }],
      dogNotes: ["Dog-friendly in campground and on roads, not dirt trails.", "Dog food goes in bear boxes."],
      warnings: ["Cal Barrel Road is 1.5-2 hours north at Prairie Creek; save it for Day 7 morning."],
    },
    {
      id: 7, label: "Day 7", date: "Thu, Jun 25",
      from: "Humboldt Redwoods, CA", to: "Eugene, OR",
      driveTime: "6-7h", miles: "~350 mi", zone: "forest",
      lodgingType: "motel", lodgingName: "Motel 6 Eugene, OR - South Springfield",
      lodgingCost: "~$58-90", lodgingNotes: "Dogs free. Book through motel6.com, property #294686.",
      lodgingBackup: "Nearby Eugene/Springfield budget motel.",
      route: "US-101 N past Eureka and Crescent City → US-199 → Grants Pass → I-5 N",
      routeNotes: "Leave by 7-8 AM. This is a real driving day, but better than the old 8-9 hour version.",
      description: "A long but scenic redwoods-to-Oregon day through Prairie Creek, Jedediah Smith, Smith River gorge, and I-5 to Eugene.",
      stops: ["Cal Barrel Road near Orick: unpaved road through 300-foot old-growth; dogs allowed because it is legally a road.", "Trinidad State Beach north of Eureka: sea stacks and dog-friendly beach.", "Howland Hill Road near Crescent City: dirt road through massive trees, dogs OK."],
      activities: ["Keep stops efficient; the route still has real miles."],
      food: [],
      dogNotes: ["Give Kye breaks every couple of hours.", "Leashed road walks are the legal redwood dog strategy."],
      warnings: ["Long drive day; start early."],
    },
    {
      id: 8, label: "Day 8", date: "Fri, Jun 26",
      from: "Eugene, OR", to: "Cannon Beach / Nehalem Bay, OR",
      driveTime: "3.5-4h", miles: "~200 mi", zone: "coastal",
      lodgingType: "camp", lodgingName: "Nehalem Bay State Park",
      lodgingCost: "~$36-50", lodgingNotes: "About 20 minutes south of Cannon Beach. 265 sites with electric and water, new showers in 2025, dog-friendly on leash. Book via oregonstateparks.reserveamerica.com.",
      lodgingBackup: "RV Resort at Cannon Beach with tent sites around $44-61 and a dog park.",
      route: "Eugene to Cannon Beach",
      routeNotes: "Aim to get beach time by afternoon.",
      description: "Oregon coast arrival day: Cannon Beach, Haystack Rock, and the low-tide magic of Hug Point.",
      stops: ["Cannon Beach and Haystack Rock.", "Hug Point, 5 minutes south; low tide only for waterfall and sea caves."],
      activities: ["Check tides.net before Hug Point.", "Let Kye enjoy Cannon Beach off-leash under voice control."],
      food: [],
      dogNotes: ["Cannon Beach allows dogs off-leash under voice control.", "Nehalem Bay State Park is leashed."],
      warnings: ["Hug Point is low tide only."],
    },
    {
      id: 9, label: "Day 9", date: "Sat, Jun 27",
      from: "Cannon Beach, OR", to: "Seattle, WA",
      driveTime: "4.5h", miles: "~230 mi", zone: "city",
      lodgingType: "airbnb", lodgingName: "Airbnb - Ballard, Seattle",
      lodgingCost: "~$150-180/night all-in", lodgingNotes: "3 nights: Sat, Sun, Mon. Look for pet-friendly Ballard place with fenced yard. Budget $115/night is too optimistic after fees.",
      lodgingBackup: "Pet-friendly Seattle hotel or nearby Airbnb if Ballard inventory is tight.",
      route: "Cannon Beach → Astoria → Seattle",
      routeNotes: "Astoria is a 30-60 minute stop.",
      description: "Coast to Seattle with an Astoria pause, then the start of three Ballard nights.",
      stops: ["Astoria Riverwalk with Kye.", "Bowpicker Fish & Chips from a boat."],
      activities: ["Ballard Locks and botanical gardens with leashed Kye.", "Magnuson Park legal off-leash dog beach on Lake Washington.", "Brewery hop: Stoup Brewing and Reuben's Brews."],
      food: [{ name: "Bowpicker Fish & Chips", note: "Astoria fish and chips from a boat." }, { name: "Stoup Brewing / Reuben's Brews", note: "Dog-friendly Ballard taprooms." }],
      dogNotes: ["Seattle beaches such as Alki do not allow dogs.", "Use Magnuson Park for legal off-leash beach time."],
      warnings: [],
    },
    {
      id: 10, label: "Day 10", date: "Sun, Jun 28",
      from: "Seattle, WA", to: "Seattle, WA",
      driveTime: "Minimal", miles: "—", zone: "city",
      lodgingType: "airbnb", lodgingName: "Airbnb - Ballard, Seattle",
      lodgingCost: "~$150-180/night all-in", lodgingNotes: "Second Ballard night.",
      lodgingBackup: "—",
      route: "Seattle explore day",
      routeNotes: "Leave Kye at the Airbnb for the crowded indoor/tourist stretch.",
      description: "Seattle explore day without Kye for the crowded attractions, then a dog-friendly skyline evening.",
      stops: ["Pike Place at 8 AM before cruise crowds.", "Space Needle.", "MoPOP.", "Chihuly.", "Capitol Hill or Fremont."],
      activities: ["Evening takeout and sunset at Gas Works Park with leashed Kye."],
      food: [],
      dogNotes: ["Kye stays at Airbnb during Pike Place, Space Needle, MoPOP, and Chihuly.", "Gas Works Park is leashed dog-friendly."],
      warnings: [],
    },
    {
      id: 11, label: "Day 11", date: "Mon, Jun 29",
      from: "Seattle, WA", to: "Seattle, WA",
      driveTime: "Minimal", miles: "—", zone: "city",
      lodgingType: "airbnb", lodgingName: "Airbnb - Ballard, Seattle",
      lodgingCost: "~$150-180/night all-in", lodgingNotes: "Third Ballard night. Sarah works from the Airbnb.",
      lodgingBackup: "—",
      route: "Seattle work day",
      routeNotes: "Sarah works; Sepehr explores with Kye.",
      description: "Work day 1 in Seattle, with a dedicated Solo Dog-Dad Day for Sepehr and Kye.",
      stops: ["9 AM Discovery Park: 2.8-mile Loop Trail, dogs on leash, forest, meadows, bluffs, Puget Sound and Olympic Mountain views.", "Noon Fremont neighborhood: Fremont Troll photo and Burke-Gilman Trail along the Ship Canal.", "1 PM Norm's Eatery & Alehouse in Fremont: dogs allowed inside, cool floor, dedicated dog menu."],
      activities: ["Evening dinner out together; leave Kye at the Airbnb.", "Try Capitol Hill or waterfront seafood."],
      food: [{ name: "Norm's Eatery & Alehouse", note: "One of the rare Seattle restaurants allowing dogs inside; dog menu includes beef nuggets and marrow bones." }],
      dogNotes: ["Discovery Park should tire Kye out.", "Norm's lets Kye rest inside while Sepehr eats."],
      warnings: [],
    },
    {
      id: 12, label: "Day 12", date: "Tue, Jun 30",
      from: "Seattle, WA", to: "Hood River, OR",
      driveTime: "4.5-5.5h", miles: "~230 mi", zone: "forest",
      lodgingType: "camp", lodgingName: "Tucker Park, Hood River County",
      lodgingCost: "~$30-40", lodgingNotes: "FCFS only. Quiet shaded forest along Hood River, 10 minutes from highway. Coin showers, potable water, no hookups. Info: 541-387-6889.",
      lodgingBackup: "Toll Bridge Park, also FCFS; cheap motel in Hood River, Cascade Locks, or The Dalles if camps are full.",
      route: "I-5 S to I-84 E",
      routeNotes: "Sarah works in the morning. Depart around 1-2 PM and expect Tacoma/Olympia afternoon I-5 traffic.",
      description: "Seattle morning work, then a late push to Hood River. Arrival is likely 6:30-8 PM.",
      stops: ["Portland Women's Forum Scenic Viewpoint if ahead of schedule."],
      activities: ["Arrive, claim FCFS site if available, keep motel backup active."],
      food: [],
      dogNotes: ["Late arrival means a short decompression walk for Kye before settling in."],
      warnings: ["FCFS arrival is late even on a Tuesday; keep the motel backup active."],
    },
    {
      id: 13, label: "Day 13", date: "Wed, Jul 1",
      from: "Hood River, OR", to: "Bend Area, OR",
      driveTime: "4-4.5h driving, 7-8h total", miles: "~150 mi", zone: "forest",
      lodgingType: "camp", lodgingName: "Tumalo State Park",
      lodgingCost: "~$30-34", lodgingNotes: "About 5 minutes from Bend. Dog-friendly with showers. Oregon nonresident pricing. Book in advance via oregonstateparks.reserveamerica.com.",
      lodgingBackup: "Nearby Bend/Tumalo campground or motel if Tumalo is full.",
      route: "Hood River → Wahclella Falls → Smith Rock → Bend",
      routeNotes: "Budget 4-4.5 hours of driving, and 7-8 hours total if you do both Wahclella Falls and Smith Rock stops.",
      description: "Gorge waterfall, Smith Rock, then Bend/Tumalo for the evening.",
      stops: ["Wahclella Falls near the Gorge: 2.4-mile dog-friendly slot canyon waterfall trail, dogs on leash.", "Smith Rock State Park en route to Bend: dogs on leash on all trails; rattlesnake alert."],
      activities: ["Walk the Deschutes River Trail: paved, flat, gorgeous.", "Crux Fermentation Project for grassy lawn, Cascade views, dogs, beer, and sunset.", "Low-stress alternative: The Bite in Tumalo, 4 minutes from camp, food-truck pod, taphouse, lawn, fire pits, string lights, aggressively dog-friendly."],
      food: [{ name: "Crux Fermentation Project", note: "Beer, sunset lawn, Cascade mountain views, dogs welcome." }, { name: "The Bite", note: "Tumalo food-truck pod with taphouse and lawn." }],
      dogNotes: ["Smith Rock requires leash and rattlesnake awareness.", "Deschutes River Trail is an easy evening Kye walk."],
      warnings: ["Rattlesnake alert at Smith Rock; stay on trail."],
    },
    {
      id: 14, label: "Day 14", date: "Thu, Jul 2",
      from: "Bend, OR", to: "Crater Lake / Prospect, OR",
      driveTime: "3.5h", miles: "~165 mi", zone: "forest",
      lodgingType: "camp", lodgingName: "Farewell Bend Campground",
      lodgingCost: "~$23-35", lodgingNotes: "Primary USFS campground near Prospect, dog-friendly. Book via recreation.gov.",
      lodgingBackup: "Natural Bridge Campground nearby; Mazama Campground inside Crater Lake NP around $23/night via recreation.gov.",
      route: "Bend south to Crater Lake North Entrance",
      routeNotes: "Hit the rim at golden hour, roughly 5-7:30 PM.",
      description: "A shorter mountain day into Crater Lake, timed for golden-hour rim views.",
      stops: ["Crater Lake North Entrance.", "Rim Village promenade.", "Beckie's Cafe in Union Creek."],
      activities: ["Dog-OK Crater Lake options: Lady of the Woods, Godfrey Glen 1-mile loop, Pinnacles Trail, PCT section, Annie Springs Spur, Grayback Rd, Rim Village promenade."],
      food: [{ name: "Beckie's Cafe", note: "Union Creek huckleberry pie." }],
      dogNotes: ["Kye is not allowed at Cleetwood Cove, the lake, or most Crater Lake trails.", "Use only the listed dog-OK paths and paved/rim areas."],
      warnings: ["Crater Lake dog access is limited; plan the visit around legal dog areas."],
    },
    {
      id: 15, label: "Day 15", date: "Fri, Jul 3",
      from: "Crater Lake, OR", to: "Hat Creek / Lassen NF, CA",
      driveTime: "4.5-5h", miles: "~230 mi", zone: "forest",
      lodgingType: "camp", lodgingName: "Hat Creek Campground or Almanor North Campground",
      lodgingCost: "Varies", lodgingNotes: "Primary plan: book whichever has reservable USFS sites on recreation.gov now. Do not rely on FCFS sites on Friday, July 3.",
      lodgingBackup: "Book a private RV park in the Mt. Shasta, Burney, or Lake Almanor area that allows tents.",
      route: "Hwy 62 E → US-97 S through Klamath Falls → Weed → I-5 S briefly → CA-89 S toward McCloud",
      routeNotes: "Alpine pine forests most of the way. Gas up at Mt. Shasta City or Burney; stations are thin on 89.",
      description: "Crater Lake to Lassen country via Mt. Shasta, CA-89, and McCloud River Falls.",
      stops: ["McCloud River Falls off CA-89: dogs on dirt trail; swim at Lower Falls may be possible depending on current, conditions, and signs.", "Mt. Shasta City Park: glacial headwaters of the Sacramento River, paved paths, dog-friendly, fill water jugs."],
      activities: ["Use Mt. Shasta City Park as the cool-down stop before CA-89.", "Arrive with a confirmed reservation; do not plan to hunt for a FCFS site after the holiday rush starts."],
      food: [],
      dogNotes: ["McCloud trail is dog-friendly on leash.", "Check signs and conditions before letting Kye swim."],
      warnings: ["Cave Campground may be FCFS and is not safe to rely on July 3. Secure a reservable Hat Creek or Almanor North site, or a private tent-friendly RV park.", "Fuel and services thin out on CA-89."],
    },
    {
      id: 16, label: "Day 16", date: "Sat, Jul 4",
      from: "Hat Creek / Lassen NF, CA", to: "Mammoth Lakes Area, CA",
      driveTime: "5.5-6h", miles: "~310 mi", zone: "desert",
      lodgingType: "camp", lodgingName: "Convict Lake Campground",
      lodgingCost: "$30-35", lodgingNotes: "Primary reservable campground via recreation.gov at 7,500+ ft. Expect around 75F days and 50F nights. Book now for July 4 weekend.",
      lodgingBackup: "Sherwin Creek or New Shady Rest; Glass Creek FCFS/free or French Camp FCFS south of Mammoth.",
      route: "CA-44 E or CA-36 E to Susanville → US-395 S",
      routeNotes: "The longest return day, but the drive is the attraction. Do not camp in Bishop: 4,100 ft and 100-105F in July is dangerous for tent plus dog.",
      description: "A full Highway 395 day through hot springs, Mono Lake, Lee Vining, and Convict Lake.",
      stops: ["Travertine Hot Springs in Bridgeport: free natural hot springs, Sierra views.", "Mono Lake South Tufa: alien calcium-carbonate towers; dogs on leash, not on State Reserve boardwalk.", "Whoa Nellie Deli at Lee Vining Mobil station: fish tacos and Mono Lake views.", "Convict Lake: turquoise alpine lake, granite peaks, flat 2-mile trail, dogs welcome, Kye may swim from shore.", "Little Lakes Valley / Mosquito Flat optional only if you arrive early with energy; do it this afternoon, not tomorrow."],
      activities: ["Stake every guy-line even if calm at 5 PM.", "Watch 395 town speed drops from 70 to 35."],
      food: [{ name: "Whoa Nellie Deli", note: "Fish tacos at the Lee Vining Mobil station with Mono Lake views." }],
      dogNotes: ["Convict Lake is the ultimate dog stop.", "Avoid Bishop camping heat with Kye."],
      warnings: ["No low-demand July 4 Sierra camping; reservations are critical.", "395 speed traps are common in small towns.", "395 wind can arrive fast; stake the tent fully."],
    },
    {
      id: 17, label: "Day 17", date: "Sun, Jul 5",
      from: "Mammoth Lakes Area, CA", to: "Escondido, CA",
      driveTime: "5.5-6.5h", miles: "~330 mi", zone: "desert",
      lodgingType: null, lodgingName: "Home!",
      lodgingCost: "—", lodgingNotes: "Leave by 6-7 AM. Home by 2-5 PM depending on Cajon Pass traffic.",
      lodgingBackup: "—",
      route: "US-395 S → Lone Pine → Red Rock Canyon → CA-14 → I-15/215 → Escondido",
      routeNotes: "Every Tahoe/Mammoth tourist is driving home; earlier departure means less I-15 Cajon Pass traffic.",
      description: "Final Mammoth-to-home push down 395 and through the desert.",
      stops: ["Alabama Hills in Lone Pine: 30-minute sunrise walk among boulders framing Mt. Whitney; dogs welcome.", "Copper Top BBQ in Big Pine: legendary tri-tip.", "Red Rock Canyon quick pullout only: dogs banned from trails, OK in picnic area."],
      activities: ["Leave camp by 6-7 AM.", "Get home by afternoon if traffic behaves."],
      food: [{ name: "Copper Top BBQ", note: "Big Pine tri-tip." }],
      dogNotes: ["Use Alabama Hills for the real morning dog walk.", "Red Rock Canyon is picnic/road only for Kye."],
      warnings: ["Leave early to reduce Cajon Pass traffic and desert heat exposure."],
    },
  ],

  driving: [
    { day: 0, date: "Thu Jun 18", from: "Escondido (7-8 PM)", to: "Ventura", miles: "~150", time: "2.75-3.5h", long: false },
    { day: 1, date: "Fri Jun 19", from: "Ventura", to: "Morro Bay", miles: "~150", time: "2.5-3h", long: false },
    { day: 2, date: "Sat Jun 20", from: "Morro Bay", to: "Monterey via Big Sur", miles: "~145", time: "3.5-4.5h", long: false },
    { day: 3, date: "Sun Jun 21", from: "Monterey/Carmel", to: "—", miles: "—", time: "Minimal", long: false },
    { day: 4, date: "Mon Jun 22", from: "Monterey", to: "San Jose", miles: "~75-120", time: "2-3h", long: false },
    { day: 5, date: "Tue Jun 23", from: "San Jose", to: "Van Damme / Mendocino", miles: "~200", time: "5.5-6.5h", long: true, flagNote: "Friend-plan long coast day" },
    { day: 6, date: "Wed Jun 24", from: "Van Damme / Mendocino", to: "Humboldt Redwoods", miles: "~155", time: "3.5-4h", long: false },
    { day: 7, date: "Thu Jun 25", from: "Humboldt", to: "Eugene", miles: "~350", time: "6-7h", long: true, flagNote: "Long day, leave 7-8 AM" },
    { day: 8, date: "Fri Jun 26", from: "Eugene", to: "Cannon Beach", miles: "~200", time: "3.5-4h", long: false },
    { day: 9, date: "Sat Jun 27", from: "Cannon Beach", to: "Seattle", miles: "~230", time: "4-4.5h", long: false },
    { day: 10, date: "Sun Jun 28", from: "Seattle", to: "—", miles: "—", time: "Minimal", long: false },
    { day: 11, date: "Mon Jun 29", from: "Seattle (work)", to: "—", miles: "—", time: "Minimal", long: false },
    { day: 12, date: "Tue Jun 30", from: "Seattle (1-2 PM)", to: "Hood River", miles: "~230", time: "4.5-5.5h", long: true, flagNote: "Late FCFS arrival" },
    { day: 13, date: "Wed Jul 1", from: "Hood River", to: "Bend area", miles: "~150", time: "4-4.5h driving", long: false, flagNote: "7-8h total with Wahclella + Smith Rock" },
    { day: 14, date: "Thu Jul 2", from: "Bend", to: "Crater Lake", miles: "~165", time: "3.5h", long: false },
    { day: 15, date: "Fri Jul 3", from: "Crater Lake", to: "Hat Creek via Shasta", miles: "~230", time: "4.5-5h", long: true, flagNote: "Holiday weekend camp risk" },
    { day: 16, date: "Sat Jul 4", from: "Hat Creek", to: "Mammoth via 395", miles: "~310", time: "5.5-6h", long: true, flagNote: "Longest return day" },
    { day: 17, date: "Sun Jul 5", from: "Mammoth", to: "Escondido", miles: "~330", time: "5.5-6.5h", long: true, flagNote: "Leave by 6-7 AM" },
  ],

  budget: {
    categories: [
      { name: "Lodging", color: "#2a7ea8", items: [
        { label: "11 camp nights (2 booked: Morro Bay $43.25, Van Damme $53.25)", amount: 394 },
        { label: "Motels: Ventura, San Jose, Eugene", amount: 240 },
        { label: "Seattle Airbnb: 3 nights (avg ~$165)", amount: 495 },
      ]},
      { name: "Transportation", color: "#8a6540", items: [
        { label: "Gas (~3,600 mi at 25 mpg, $4.50/gal)", amount: 650 },
      ]},
      { name: "Food", color: "#c8832a", items: [
        { label: "Food (~$50/day x 18 days for 2)", amount: 900 },
      ]},
      { name: "Dog", color: "#8b4f3c", items: [
        { label: "Dog fees: camp/Airbnb pet fees", amount: 80 },
      ]},
      { name: "Misc", color: "#6b6060", items: [
        { label: "Firewood, supplies, parking", amount: 150 },
        { label: "Contingency", amount: 200 },
        { label: "Plan estimate buffer / fee rounding", amount: 97 },
      ]},
    ]
  },

  bookings: [
    { p: 1, what: "Morro Bay SP Upper Section, Site 123 (Jun 19)", how: "ReserveCalifornia / Web Bookings", urgency: "critical", notes: "BOOKED: confirmation #29558779, $43.25 paid", status: "booked" },
    { p: 2, what: "Van Damme SP Upper Loop, Site 033 (Jun 23)", how: "ReserveCalifornia / Web Bookings", urgency: "critical", notes: "BOOKED: confirmation #29557920, $53.25 paid", status: "booked" },
    { p: 3, what: "Nehalem Bay State Park (Jun 26)", how: "oregonstateparks.reserveamerica.com", urgency: "critical", notes: "Oregon coast summer demand", status: "pending" },
    { p: 4, what: "Burlington CG, Humboldt Redwoods (Jun 24)", how: "ReserveCalifornia", urgency: "critical", notes: "Book now", status: "pending" },
    { p: 5, what: "Convict Lake CG (Jul 4)", how: "recreation.gov", urgency: "critical", notes: "July 4 weekend", status: "pending" },
    { p: 6, what: "Hat Creek or Almanor North Campground (Jul 3)", how: "recreation.gov", urgency: "critical", notes: "Do not rely on FCFS Cave CG for July 4 weekend", status: "pending" },
    { p: 7, what: "Farewell Bend or Natural Bridge CG (Jul 2)", how: "recreation.gov / USFS", urgency: "very-high", notes: "Crater Lake area", status: "pending" },
    { p: 8, what: "Tumalo State Park (Jul 1)", how: "oregonstateparks.reserveamerica.com", urgency: "very-high", notes: "Bend area", status: "pending" },
    { p: 9, what: "Seattle Airbnb (Jun 27-29, 3 nights)", how: "Airbnb", urgency: "high", notes: "Ballard, pet-friendly, fenced yard", status: "pending" },
    { p: 10, what: "Laguna Seca backup (Jun 20-21)", how: "Call 888-588-2267", urgency: "high", notes: "Ask about track events for full weekend", status: "pending" },
    { p: 11, what: "Motel 6 Ventura Beach (Jun 18)", how: "motel6.com", urgency: "moderate", notes: "Night 0", status: "pending" },
    { p: 12, what: "Motel 6 San Jose South (Jun 22)", how: "motel6.com", urgency: "moderate", notes: "Bay Area night", status: "pending" },
    { p: 13, what: "Motel 6 Eugene South (Jun 25)", how: "motel6.com", urgency: "moderate", notes: "Property #294686", status: "pending" },
    { p: 14, what: "Veterans Memorial Park, Monterey", how: "FCFS only", urgency: "high", notes: "Arrive Sat Jun 20 by noon", status: "pending" },
    { p: 15, what: "Tucker Park (Jun 30)", how: "FCFS only", urgency: "high", notes: "Arrive Tuesday evening; keep motel backup", status: "pending" },
  ],

  dogRules: [
    { location: "Morro Bay SP, CA", allowed: ["Campground on leash", "Developed areas and waterfront walks where posted dog rules allow"], notAllowed: ["Signed wildlife-sensitive areas", "Most dirt state park trails unless specifically posted dog-friendly"], notes: "Booked site 123 for Jun 19." },
    { location: "Pismo Beach, CA", allowed: ["Beach walks on leash during an optional stop"], notAllowed: ["Oso Flaco", "Dunes Preserve"], notes: "Pismo is now an optional stop, not the overnight camp." },
    { location: "Van Damme SP, CA", allowed: ["Campground on leash", "Developed areas"], notAllowed: ["Restricted state park trails"], notes: "Booked Upper Loop site 033 for Jun 23." },
    { location: "Carmel Beach, CA", allowed: ["OFF-LEASH under voice control within 25 ft", "Carmel village patios"], notAllowed: ["Scenic Pathway"], notes: "One of the biggest Kye highlights." },
    { location: "Cannon Beach, OR", allowed: ["OFF-LEASH under voice control", "Beach walks"], notAllowed: ["Wildlife protection areas"], notes: "Keep extra distance around birds and tidepool zones." },
    { location: "Seattle Beaches", allowed: ["Magnuson Park off-leash area only", "Ballard Locks and Gas Works on leash"], notAllowed: ["Alki and other regular Seattle beaches"], notes: "Seattle beach rules are stricter than Oregon coast rules." },
    { location: "Humboldt Redwoods", allowed: ["Campgrounds", "Paved/developed areas", "Avenue of the Giants pullouts", "Mattole Road shoulder"], notAllowed: ["All dirt trails"], notes: "Cal Barrel Road and Howland Hill Road are farther north on Day 7, not Humboldt Redwoods." },
    { location: "Crater Lake NP", allowed: ["Rim Village promenade", "Lady of the Woods", "Godfrey Glen", "PCT section", "Pinnacles", "Annie Springs Spur", "Grayback Rd"], notAllowed: ["Cleetwood Cove", "The lake", "Most trails"], notes: "Use only the specific dog-OK areas." },
    { location: "Smith Rock, OR", allowed: ["All trails on leash"], notAllowed: ["Off-leash hiking"], notes: "Rattlesnake alert: stay on trail." },
    { location: "Wahclella Falls, OR", allowed: ["Full trail on leash"], notAllowed: ["Off-leash hiking"], notes: "2.4-mile dog-friendly waterfall trail." },
    { location: "McCloud River Falls", allowed: ["Trail on leash", "Possible swim at Lower Falls if safe and posted signs allow"], notAllowed: ["Unsafe current or restricted swim areas"], notes: "Check signs and conditions before Kye swims." },
    { location: "Convict Lake", allowed: ["Trail on leash", "Shore access", "Possible swim from shore"], notAllowed: ["Disturbing wildlife"], notes: "The plan's ultimate dog stop." },
    { location: "Mono Lake South Tufa", allowed: ["Tufa area on leash"], notAllowed: ["State Reserve boardwalk"], notes: "Keep to dog-legal sections." },
    { location: "Red Rock Canyon SP", allowed: ["Campground, picnic areas, roads"], notAllowed: ["Trails"], notes: "Day 17 is quick pullout only." },
    { location: "Alabama Hills", allowed: ["BLM dog-friendly walking"], notAllowed: ["Unsafe heat exposure"], notes: "Best final-day sunrise dog walk." },
  ],

  food: [
    { name: "Splash Cafe", loc: "Pismo Beach, CA", day: 1, type: "seafood", desc: "Optional clam chowder bread bowl stop en route to Morro Bay.", dog: false },
    { name: "Princess Seafood Market", loc: "Fort Bragg, CA", day: 5, type: "seafood", desc: "Crab rolls on the dock.", dog: true },
    { name: "Eel River Brewing", loc: "Fortuna, CA", day: 6, type: "brewery", desc: "Massive dog patio after the redwoods.", dog: true },
    { name: "Bowpicker Fish & Chips", loc: "Astoria, OR", day: 9, type: "seafood", desc: "Fish and chips served from a boat.", dog: true },
    { name: "Stoup Brewing / Reuben's Brews", loc: "Ballard, Seattle", day: 9, type: "brewery", desc: "Dog-friendly taprooms for the Seattle arrival evening.", dog: true },
    { name: "Norm's Eatery & Alehouse", loc: "Fremont, Seattle", day: 11, type: "pub", desc: "Dogs allowed inside, cool floor, dedicated dog menu.", dog: true },
    { name: "Crux Fermentation Project", loc: "Bend, OR", day: 13, type: "brewery", desc: "Beer, grassy sunset lawn, Cascade mountain views, dogs welcome.", dog: true },
    { name: "The Bite", loc: "Tumalo, OR", day: 13, type: "pub", desc: "Low-stress dog-friendly food-truck pod with lawn and central taphouse.", dog: true },
    { name: "Beckie's Cafe", loc: "Union Creek, OR", day: 14, type: "cafe", desc: "Huckleberry pie near Crater Lake.", dog: false },
    { name: "Whoa Nellie Deli", loc: "Lee Vining, CA", day: 16, type: "diner", desc: "Fish tacos at the Mobil station with Mono Lake views.", dog: true },
    { name: "Copper Top BBQ", loc: "Big Pine, CA", day: 17, type: "restaurant", desc: "Legendary tri-tip on the final 395 drive.", dog: true },
  ],

  packing: [
    { cat: "🐾 Dog", items: ["6-foot leash, no retractables", "Collapsible water bowl + extra water jugs", "Dog booties (Ruffwear Grip Trex)", "Cooling vest (Ruffwear Swamp Cooler)", "Tweezers + headlamp for nightly foxtail checks", "Poop bags, dog first aid kit", "Blanket/bed for tent", "Vaccination records + ID tags", "Photo of Kye on phone", "Fresh flea/tick preventative dose this week"] },
    { cat: "🏕 Camping", items: ["Tent with removable rainfly", "Aluminet shade cloth", "Bear canister or plan for bear lockers", "Warm layers for coast/mountains + light clothing for valleys", "Rain jacket for Oregon coast", "Battery-powered fan", "Headlamp", "Portable power bank for non-electric camp nights", "Firewood money ($8-12/bundle, do not transport across state lines)", "3 extra gallons emergency water", "Baby oil + rag for beach tar removal"] },
    { cat: "📱 Apps", items: ["Watch Duty for wildfire checks", "Caltrans QuickMap for road closures", "tides.net / NOAA for Hug Point timing", "Campflare or Campnab for cancellation alerts", "iOverlander + Campendium for dispersed camping GPS"] },
    { cat: "💻 Work", items: ["Laptop + charger", "Portable wifi hotspot as optional backup"] },
  ],

  todos: [
    { cat: "Book Now", items: ["BOOKED: Morro Bay SP Upper Section site 123 (Jun 19), confirmation #29558779", "BOOKED: Van Damme SP Upper Loop site 033 (Jun 23), confirmation #29557920", "Nehalem Bay SP (Jun 26) via oregonstateparks.reserveamerica.com", "Burlington CG, Humboldt Redwoods (Jun 24) via ReserveCalifornia", "Convict Lake CG (Jul 4) via recreation.gov", "Hat Creek or Almanor North CG (Jul 3) via recreation.gov, or private tent-friendly RV park backup", "Farewell Bend or Natural Bridge CG (Jul 2) via recreation.gov", "Tumalo State Park (Jul 1) via oregonstateparks.reserveamerica.com", "Seattle Airbnb: 3 nights Jun 27-29, Ballard, pet-friendly, fenced yard", "Call Laguna Seca (888-588-2267): Jun 20-21 tent site, dog policy, track events", "Motel 6 Ventura Beach (Jun 18)", "Motel 6 San Jose South (Jun 22)", "Motel 6 Eugene South (Jun 25)"] },
    { cat: "Gear & Car", items: ["Oil change", "Tire check including spare", "AC and coolant systems topped off", "Buy baby oil, extra water jugs, power bank", "Bear canister check / confirm campground bear lockers"] },
    { cat: "Dog Prep", items: ["Fresh flea/tick preventative dose this week", "Bootie training at home (let Kye do the moonwalk)", "Confirm vaccination records are current"] },
  ],
};
