'use strict';

const TRIP_DATA = {
  meta: {
    title: "The Adventure of Sarah, Sepehr & Kye",
    subtitle: "West Coast Loop: Escondido to Seattle and Back",
    dates: "June 18 (evening) - July 5, 2026",
    totalMiles: "~3,700",
    estimatedDriveTime: "~53-60h",
  },
  stats: [
    { value: "~3,700", label: "miles" },
    { value: "12", label: "camp nights" },
    { value: "2", label: "motel nights" },
    { value: "3", label: "Airbnb nights" },
    { value: "1 dog", label: "Kye on tour" },
  ],
  warnings: [
    { icon: "🐕", title: "Trail Restrictions", sev: "high", desc: "Dogs are banned from dirt trails in nearly all CA State Parks and National Parks. Use campgrounds, paved paths, roads, National Forests, Oregon, and beaches for real dog time." },
    { icon: "🌾", title: "Foxtails", sev: "high", desc: "Barbed seeds can burrow into paws, ears, and noses. Check Kye's paws between toes and ears every night with a headlamp; pack tweezers." },
    { icon: "🐍", title: "Rattlesnakes", sev: "high", desc: "Peak risk in Columbia Gorge, Smith Rock, and the Eastern Sierra floor. Keep Kye on a strict 6-foot leash with no retractable leash." },
    { icon: "🐻", title: "Bear Country", sev: "high", desc: "Redwoods, Lassen NF, and the Eastern Sierra require bear discipline. Dog food goes in bear lockers or approved storage, never in the tent." },
    { icon: "🪨", title: "Volcanic Terrain", sev: "medium", desc: "Bend, Crater Lake, and Lassen areas can have sharp pumice. Dog booties such as Ruffwear Grip Trex are strongly recommended." },
    { icon: "🌡", title: "Heat + Tent", sev: "high", desc: "Remove the rainfly on hot days. Bring a cooling vest, Aluminet shade cloth, and extra water." },
    { icon: "🔥", title: "Wildfire Checks", sev: "high", desc: "Use Watch Duty every morning for real-time wildfire tracking and route decisions." },
    { icon: "💧", title: "Remote Water", sev: "medium", desc: "Carry 3 extra gallons of water in the trunk. Shasta, Lassen, and Highway 395 stretches are remote." },
    { icon: "🛣", title: "Big Sur Hwy 1", sev: "high", desc: "Hwy 1 reopened in Jan 2026 but remains slide-prone. Check Caltrans QuickMap the morning of the drive. Backup is US-101 via Paso Robles and Salinas." },
    { icon: "🏕", title: "Camping Availability", sev: "high", desc: "Humbug Mountain on Jun 25 and Barview Jetty on Jun 26 are booked. Reserve Millersylvania for Jun 27 immediately and keep private-campground backups." },
    { icon: "🎆", title: "July 3-4", sev: "high", desc: "No low-demand FCFS Sierra camping on July 4 weekend. Book reservable sites now and download iOverlander and Campendium for dispersed backups." },
    { icon: "⛺", title: "Tent Fatigue", sev: "medium", desc: "Days 5-9 are five consecutive setup and breakdown nights: Van Damme, Burlington, Humbug Mountain, Barview Jetty, and Millersylvania. Keep these camp setups ruthlessly simple." },
    { icon: "🐕", title: "Oregon Coast Dog Rules", sev: "high", desc: "Voice-control off-leash access is common on wet packed sand where posted rules allow, but dogs are strictly banned from dry sand behind yellow Snowy Plover nesting signs from Mar 15-Sep 15." },
  ],
  days: [
    {
      id: 0, label: "Night 0", date: "Thu, Jun 18",
      from: "Escondido, CA", to: "Ventura, CA",
      driveTime: "2.75-3.5h", miles: "~150 mi", zone: "coastal",
      lodgingType: "motel", lodgingName: "Motel 6 Ventura, CA - Beach",
      lodgingCost: "~$75-90", lodgingNotes: "1.5 blocks from beach. Free wifi, pool, free parking, dogs free. Book through motel6.com.",
      lodgingBackup: "Nearby cheap Ventura motel if Motel 6 fills.",
      route: "Evening freeway push past LA traffic",
      routeNotes: "Depart around 7-8 PM, arrive around 10 PM, sleep.",
      description: "Leave Thursday evening and skip LA traffic entirely. This is just the clean launch pad for the coast route.",
      stops: ["No sightseeing required; the win is getting north of Los Angeles."],
      activities: ["Arrive, quick Kye walk, sleep."],
      food: [],
      dogNotes: ["Dogs free at Motel 6.", "Keep the arrival routine simple so Kye settles quickly."],
      warnings: [],
    },
    {
      id: 1, label: "Day 1", date: "Fri, Jun 19",
      from: "Ventura, CA", to: "Morro Bay, CA",
      driveTime: "2.5-3h", miles: "~150 mi", zone: "coastal",
      lodgingType: "camp", lodgingName: "Morro Bay SP - Upper Section, Site 123",
      lodgingCost: "$43.25 paid", lodgingNotes: "BOOKED. Stay Fri 06/19/2026 2:00 PM to Sat 06/20/2026 12:00 PM. Upper Section sites 86-140, campsite 123. Confirmation #29558779. Purchased 06/03/2026. Regular campsite, active reservation; $35 campsite + $8.25 reservation fee.",
      lodgingBackup: "No backup needed for Jun 19 unless the reservation changes.",
      route: "US-101 N → CA-1 / Morro Bay",
      routeNotes: "Sarah works from motel wifi until late-morning checkout, then you head north with no rush.",
      description: "A gentle first coast day after Sarah's work morning. The first camp night is now locked at Morro Bay, which makes the next morning's Big Sur launch easy.",
      stops: ["Fiscalini Ranch Preserve in Cambria: free, dog-friendly ocean boardwalks.", "Optional Pismo detour for pier walk or Splash Cafe if timing feels easy.", "Morro Rock / Embarcadero evening walk."],
      activities: ["Check into Morro Bay SP after 2 PM.", "Morro Bay waterfront sunset walk with leashed Kye.", "Keep the first camp setup simple and organized."],
      food: [{ name: "Splash Cafe", note: "Optional Pismo stop for clam chowder bread bowl." }],
      dogNotes: ["Morro Bay SP campground allows dogs on leash.", "Use Morro Bay waterfront and developed paths for Kye; avoid signed wildlife-sensitive areas."],
      warnings: ["Reservation is active; bring confirmation #29558779."],
    },
    {
      id: 2, label: "Day 2", date: "Sat, Jun 20",
      from: "Morro Bay", to: "Monterey / Carmel",
      driveTime: "3.5-4.5h", miles: "~145 mi", zone: "coastal",
      lodgingType: "camp", lodgingName: "Veterans Memorial Park, Monterey",
      lodgingCost: "~$47", lodgingNotes: "In-town FCFS campground with hot showers and no electricity. No reservations. Go directly here on arrival and try for 2 nights.",
      lodgingBackup: "Laguna Seca Recreation Area; call 888-588-2267 and confirm no race or track event.",
      route: "CA-1 / Hwy 1 through Big Sur",
      routeNotes: "Break camp by the noon checkout, but still aim to leave early. Check Caltrans QuickMap for Hwy 1 status. Backup is US-101 via Paso Robles and Salinas.",
      description: "Big Sur is the drive: a dramatic 90-mile coastal stretch of Hwy 1. Monterey and Carmel are the destination.",
      stops: ["Garrapata State Park Gate 19: cliffside dirt trails, leashed dogs allowed.", "Rocky Creek Bridge north of Bixby: similar architecture, fewer crowds.", "Pfeiffer Beach: leashed dogs OK."],
      activities: ["Arrive Monterey by noon-1 PM when FCFS camps may open.", "If only one night is available at Veterans Memorial, take it and use Laguna Seca for the other night."],
      food: [],
      dogNotes: ["Garrapata Gate 19 is the Big Sur dog hike.", "Carmel Beach is a short drive once camp is secured."],
      warnings: ["Hwy 1 is slide-prone; check Caltrans QuickMap that morning."],
    },
    {
      id: 3, label: "Day 3", date: "Sun, Jun 21",
      from: "Monterey / Carmel", to: "Monterey / Carmel",
      driveTime: "Minimal", miles: "—", zone: "coastal",
      lodgingType: "camp", lodgingName: "Veterans Memorial Park or Laguna Seca",
      lodgingCost: "~$47+", lodgingNotes: "Second Monterey-area night from Day 2's campsite plan.",
      lodgingBackup: "Use Laguna Seca if Veterans Memorial only had one night.",
      route: "Local Monterey and Carmel hops",
      routeNotes: "Friends arrive; keep the car time minimal.",
      description: "Full day with friends in Monterey and Carmel, built around dog-friendly coastal time.",
      stops: ["Carmel Beach.", "Carmel village.", "Monterey Fisherman's Wharf."],
      activities: ["Carmel Beach is legally off-leash for dogs under voice control within 25 ft.", "Walk Carmel village patios and Monterey Fisherman's Wharf with Kye on leash."],
      food: [],
      dogNotes: ["Carmel Beach is a trip highlight for Kye.", "Use voice control and stay within the 25 ft rule."],
      warnings: [],
    },
    {
      id: 4, label: "Day 4", date: "Mon, Jun 22",
      from: "Monterey, CA", to: "San Jose, CA",
      driveTime: "2-3h", miles: "~75-120 mi", zone: "city",
      lodgingType: "motel", lodgingName: "Motel 6 San Jose, CA - South",
      lodgingCost: "~$84-97", lodgingNotes: "2 pets up to 150 lbs. $0 pet fee. Book through motel6.com.",
      lodgingBackup: "Nearby San Jose motel if needed.",
      route: "Monterey brunch → 17-Mile Drive → Santa Cruz → optional Half Moon Bay → San Jose",
      routeNotes: "This is the friends' plan day.",
      description: "A friend-plan transition day from Monterey into the Bay Area.",
      stops: ["Morning brunch in Monterey.", "17-Mile Drive with dogs in the car.", "Santa Cruz.", "Optional Half Moon Bay."],
      activities: ["Keep the day flexible and social."],
      food: [],
      dogNotes: ["17-Mile Drive is dog-friendly from the car and viewpoints.", "Motel 6 has no pet fee."],
      warnings: [],
    },
    {
      id: 5, label: "Day 5", date: "Tue, Jun 23",
      from: "San Jose, CA", to: "Van Damme SP / Mendocino, CA",
      driveTime: "5.5-6.5h", miles: "~200 mi", zone: "coastal",
      lodgingType: "camp", lodgingName: "Van Damme SP - Upper Loop, Site 033",
      lodgingCost: "$53.25 paid", lodgingNotes: "BOOKED. Stay Tue 06/23/2026 2:00 PM to Wed 06/24/2026 12:00 PM. Upper Loop sites 31-74, campsite 033. Confirmation #29557920. Purchased 06/03/2026. Regular campsite, active reservation; $45 campsite + $8.25 reservation fee.",
      lodgingBackup: "No backup needed for Jun 23 unless the reservation changes.",
      route: "Golden Gate → Sonoma Coast → Mendocino headlands",
      routeNotes: "This is the longest friend-plan coast day.",
      description: "Bay Area to the Mendocino coast by way of the Golden Gate, Sonoma Coast, and a booked night at Van Damme State Park.",
      stops: ["Golden Gate walk: leashed dogs on pedestrian path.", "Sonoma Coast.", "Mendocino headlands."],
      activities: ["Check into Van Damme SP after 2 PM.", "Evening coastal walk if time allows."],
      food: [{ name: "Princess Seafood Market", note: "Fort Bragg crab rolls on the dock." }],
      dogNotes: ["Golden Gate pedestrian path allows leashed dogs.", "Van Damme campground allows leashed dogs; keep Kye out of restricted park trails.", "Watch foxtails along dry coastal edges."],
      warnings: ["Reservation is active; bring confirmation #29557920."],
    },
    {
      id: 6, label: "Day 6", date: "Wed, Jun 24",
      from: "Van Damme SP / Mendocino, CA", to: "Humboldt Redwoods, CA",
      driveTime: "2.5h direct; 4-5h with stops", miles: "~100 mi", zone: "forest",
      lodgingType: "camp", lodgingName: "Humboldt Redwoods SP - Burlington Camp, Tent Site 004Bu",
      lodgingCost: "$43.25 paid", lodgingNotes: "BOOKED. Stay Wed 06/24/2026 2:00 PM to Thu 06/25/2026 12:00 PM. Regular tent campsite 004Bu; confirmation #29559795, purchased 06/03/2026. $35 campsite + $8.25 reservation fee. Right on Avenue of the Giants by the visitor center; dog-friendly on 6 ft leash, coin showers, flush toilets, bear boxes.",
      lodgingBackup: "No backup needed for Jun 24 unless the reservation changes.",
      route: "Mendocino connector → US-101 N → Avenue of the Giants",
      routeNotes: "Direct driving is about 2.5 hours; allow 4-5 hours total for Avenue of the Giants stops.",
      description: "The booked Burlington Camp is the original intended Humboldt Redwoods campground beside park headquarters and the visitor center.",
      stops: ["Avenue of the Giants: 32-mile scenic drive through old-growth.", "Rockefeller Forest via Mattole Road: walk leashed Kye along the county road shoulder under huge canopies.", "Eel River gravel bars by Burlington Campground."],
      activities: ["Drive slowly and pull over at every grove.", "Let Kye swim and fetch in the slow, shallow South Fork Eel River if conditions are safe.", "Evening grove pullouts for redwood light."],
      food: [{ name: "Eel River Brewing", note: "Fortuna; massive dog patio." }],
      dogNotes: ["Dog-friendly in campground and on roads, not dirt trails.", "Dog food goes in bear boxes."],
      warnings: ["Reservation is active; bring confirmation #29559795.", "Cal Barrel Road is 1.5-2 hours north at Prairie Creek; save it for Day 7 morning."],
    },
    {
      id: 7, label: "Day 7", date: "Thu, Jun 25",
      from: "Burlington Camp, Humboldt Redwoods", to: "Humbug Mountain State Park, OR",
      driveTime: "3.5-4h", miles: "~185 mi", zone: "coastal",
      lodgingType: "camp", lodgingName: "Humbug Mountain State Park - Tent Site 54",
      lodgingCost: "$50.00 paid", lodgingNotes: "BOOKED. Stay Thu 06/25/2026 4:00 PM to Fri 06/26/2026 1:00 PM. Tent site 54, loop 28-95. Reservation #2-38213261, ordered Thu 06/04/2026 at 10:35 AM PDT. Confirmed overnight tent-site reservation for 2 occupants and 1 vehicle. $40 camping fee + $10 reservation fee = $50 paid; balance $0. Tucked in a lush valley east of Hwy 101 with showers, flush toilets, and beach access via a 0.5-mile walk under the highway.",
      lodgingBackup: "No backup needed for Jun 25 unless the reservation changes.",
      route: "US-101 N through Prairie Creek and Crescent City → Southern Oregon Coast",
      routeNotes: "Cross from the California Redwoods into the rugged Southern Oregon Coast.",
      description: "Redwood-road detours in the morning, then staggering Southern Oregon cliff views before a protected coastal camp.",
      stops: ["Cal Barrel Road at Prairie Creek or Howland Hill Road near Jed Smith for a quick legal dirt-road walk among the giants.", "Samuel H. Boardman State Scenic Corridor: Arch Rock or Natural Bridges cliffside views."],
      activities: ["Walk the 0.5-mile beach-access route from camp if timing and conditions are comfortable."],
      food: [],
      dogNotes: ["Keep Kye leashed on redwood road shoulders and in the campground.", "Obey all posted Oregon Coast beach restrictions."],
      warnings: ["Reservation is confirmed; bring reservation #2-38213261.", "The camp gets shady and damp early."],
    },
    {
      id: 8, label: "Day 8", date: "Fri, Jun 26",
      from: "Humbug Mountain State Park, OR", to: "Barview Jetty / Rockaway Beach, OR",
      driveTime: "5.5-6h driving; 7.5h+ total", miles: "~230 mi", zone: "coastal",
      lodgingType: "camp", lodgingName: "Barview Jetty County Campground - Blue Tent Site C2",
      lodgingCost: "$46.00 paid", lodgingNotes: "BOOKED. Stay Fri 06/26/2026 3:30 PM to Sat 06/27/2026 1:30 PM. Blue Tent Site C2. Confirmation #R00000007782; invoice #I00000016761; ordered Thu 06/04/2026. Confirmed for 2 adults and Kye. $32 base fee + $11 reservation fee + $3 booking fee = $46 paid; balance $0. Tillamook County campground at the mouth of Tillamook Bay with massive beaches. This is not a state park.",
      lodgingBackup: "No backup needed for Jun 26 unless the reservation changes.",
      route: "US-101 N along the Oregon Coast",
      routeNotes: "Expect slow RVs and 25-35 mph coastal-town limits. Start early, pack patience, and do not over-plan stops.",
      description: "A long but incredibly scenic Oregon Coast day with just two deliberate stops.",
      stops: ["Face Rock State Scenic Viewpoint in Bandon: epic wide beach for Kye to stretch.", "Cape Perpetua near Yachats: paved paths overlooking Thor's Well."],
      activities: ["Stake the tent down heavily and seek a Barview site nestled in the trees."],
      food: [],
      dogNotes: ["Keep Kye strictly on wet packed sand during Snowy Plover nesting season.", "Obey every yellow nesting-restriction sign."],
      warnings: ["Deadly sneaker-wave risk on coastal rocks.", "Barview can be very windy; stake every guy-line.", "Reservation is confirmed; bring confirmation #R00000007782."],
    },
    {
      id: 9, label: "Day 9", date: "Sat, Jun 27",
      from: "Barview Jetty, OR", to: "Millersylvania / Olympia, WA",
      driveTime: "3-3.5h", miles: "~145 mi", zone: "coastal",
      lodgingType: "camp", lodgingName: "Millersylvania State Park",
      lodgingCost: "~$32-37", lodgingNotes: "PROPOSED, NOT YET BOOKED. Old-growth forest campground on Deep Lake. Dogs must remain on a strict 8-foot leash and are not allowed on human swimming beaches. Book via washington.goingtocamp.com.",
      lodgingBackup: "Another reservable Olympia/Tacoma-area campground.",
      route: "US-101 N through Cannon Beach and Astoria → Megler Bridge → inland to Olympia",
      routeNotes: "Arrive early at Cannon Beach because Saturday parking will be tight.",
      description: "Northern Oregon Coast highlights, Astoria, and the 4-mile Megler Bridge before turning inland to Washington.",
      stops: ["Cannon Beach / Hug Point for iconic dog running near Haystack Rock.", "Astoria for Bowpicker Fish & Chips and a waterfront walk.", "Cross the massive 4-mile Megler Bridge into Washington."],
      activities: ["Settle into Millersylvania's old-growth Deep Lake campground."],
      food: [{ name: "Bowpicker Fish & Chips", note: "Astoria fish and chips from a boat." }],
      dogNotes: ["Dogs must be leashed at all times, including in the water.", "Dogs are not allowed at the two designated human swimming beaches."],
      warnings: ["Saturday parking at Cannon Beach will be tight; arrive early.", "Book Millersylvania immediately via Washington State Parks."],
    },
    {
      id: 10, label: "Day 10", date: "Sun, Jun 28",
      from: "Millersylvania / Olympia, WA", to: "Seattle, WA",
      driveTime: "1.75-2h", miles: "~77 mi", zone: "city",
      lodgingType: "airbnb", lodgingName: "Airbnb - Ballard, Seattle",
      lodgingCost: "~$150-180/night all-in", lodgingNotes: "First of 2 nights: Sun + Mon. Find a pet-friendly Ballard place with a fenced yard.",
      lodgingBackup: "Pet-friendly Seattle hotel or nearby Airbnb if Ballard inventory is tight.",
      route: "Millersylvania → I-5 N → Ballard",
      routeNotes: "Pack after breakfast and arrive around late morning or early afternoon, depending on Airbnb check-in.",
      description: "The short final approach delivers a relaxed Seattle arrival day.",
      stops: ["Ballard Locks and botanical gardens.", "Magnuson Park legal off-leash dog beach."],
      activities: ["Brewery hop at Stoup Brewing and Reuben's Brews.", "Use the arrival afternoon as Kye's Seattle dog day."],
      food: [{ name: "Stoup Brewing / Reuben's Brews", note: "Dog-friendly Ballard taprooms." }],
      dogNotes: ["Seattle beaches such as Alki do not allow dogs.", "Use Magnuson Park for legal off-leash beach time."],
      warnings: [],
    },
    {
      id: 11, label: "Day 11", date: "Mon, Jun 29",
      from: "Seattle, WA", to: "Seattle, WA",
      driveTime: "Minimal", miles: "—", zone: "city",
      lodgingType: "airbnb", lodgingName: "Airbnb - Ballard, Seattle",
      lodgingCost: "~$150-180/night all-in", lodgingNotes: "Second and final Ballard night. Sarah works from the Airbnb.",
      lodgingBackup: "—",
      route: "Seattle work day",
      routeNotes: "Sarah works; Sepehr explores with Kye.",
      description: "Work day 1 in Seattle, with a dedicated Solo Dog-Dad Day for Sepehr and Kye.",
      stops: ["9 AM Discovery Park: 2.8-mile Loop Trail, dogs on leash, forest, meadows, bluffs, Puget Sound and Olympic Mountain views.", "Noon Fremont neighborhood: Fremont Troll photo and Burke-Gilman Trail along the Ship Canal.", "1 PM Norm's Eatery & Alehouse in Fremont: dogs allowed inside, cool floor, dedicated dog menu."],
      activities: ["Evening dinner out together; leave Kye at the Airbnb.", "Optional Pike Place, Space Needle, MoPOP, Chihuly, Capitol Hill, Fremont, or Gas Works Park while taking turns with Kye."],
      food: [{ name: "Norm's Eatery & Alehouse", note: "One of the rare Seattle restaurants allowing dogs inside; dog menu includes beef nuggets and marrow bones." }],
      dogNotes: ["Discovery Park should tire Kye out.", "Norm's lets Kye rest inside while Sepehr eats."],
      warnings: [],
    },
    {
      id: 12, label: "Day 12", date: "Tue, Jun 30",
      from: "Seattle, WA", to: "Portland, OR",
      driveTime: "3-4h", miles: "~175 mi", zone: "city",
      lodgingType: "airbnb", lodgingName: "Airbnb - SE Portland",
      lodgingCost: "~$170-230 all-in", lodgingNotes: "One pet-friendly night in Inner Southeast Portland: Hawthorne, Division, or Belmont. North Portland Mississippi/Williams is the runner-up.",
      lodgingBackup: "Pet-friendly Portland hotel or Airbnb with easy street access.",
      route: "I-5 S from Seattle to Portland",
      routeNotes: "Sarah works in the morning. Depart around 1-2 PM; Tacoma/Olympia traffic can bite. Arrive around 5-6 PM, or 6:30 if traffic is ugly.",
      description: "A much shorter post-work drive than the old Hood River push, with a comfortable Portland city night.",
      stops: ["Mt. Tabor Park the next morning: off-leash dog park and paved summit paths.", "Avoid Forest Park trailheads with a car full of camping gear due to break-in risk."],
      activities: ["Hawthorne Asylum Food Carts.", "Lucky Labrador Brew Pub or Baerlic Brewing."],
      food: [{ name: "Hawthorne Asylum / Lucky Labrador / Baerlic", note: "Dog-friendly Portland food carts and breweries." }],
      dogNotes: ["SE Portland is leafy and walkable for quick dog breaks.", "Use Mt. Tabor, not Forest Park, for the morning walk."],
      warnings: ["Do not leave the gear-packed car at Forest Park trailheads."],
    },
    {
      id: 13, label: "Day 13", date: "Wed, Jul 1",
      from: "Portland, OR", to: "Bend Area, OR",
      driveTime: "3-3.5h direct; 4.5-5.5h with stops", miles: "~160 mi", zone: "forest",
      lodgingType: "camp", lodgingName: "Tumalo State Park",
      lodgingCost: "~$30-34", lodgingNotes: "About 5 minutes from Bend. Dog-friendly with showers. Oregon nonresident pricing. Book in advance via oregonstateparks.reserveamerica.com.",
      lodgingBackup: "Nearby Bend/Tumalo campground or motel if Tumalo is full.",
      route: "US-26 E over Mt. Hood → Warm Springs → Madras → US-97 S",
      routeNotes: "The Mt. Hood route is more direct and scenic than the Gorge. Do not stop at Smith Rock today; it is moved to dawn on Day 14.",
      description: "Mt. Hood, Trillium Lake, and a comfortable Bend arrival without exposing Kye to afternoon Smith Rock heat.",
      stops: ["Mt. Tabor morning walk before leaving Portland.", "Trillium Lake: flat 2-mile loop, Mt. Hood reflection, and leashed shore swimming.", "Frog Lake backup if Trillium is crowded.", "Mt. Hood Brewing patio lunch in Government Camp."],
      activities: ["Walk the Deschutes River Trail: paved, flat, gorgeous.", "Crux Fermentation Project for grassy lawn, Cascade views, dogs, beer, and sunset.", "Low-stress alternative: The Bite in Tumalo, 4 minutes from camp, food-truck pod, taphouse, lawn, fire pits, string lights, aggressively dog-friendly."],
      food: [{ name: "Mt. Hood Brewing", note: "Government Camp patio lunch with mountain views." }, { name: "Crux Fermentation Project / The Bite", note: "Dog-friendly Bend and Tumalo evening options." }],
      dogNotes: ["Trillium Lake is a top leashed swim stop.", "Deschutes River Trail is an easy evening Kye walk."],
      warnings: ["Skip Smith Rock this afternoon; heat, paw-pad risk, and rattlesnakes make dawn safer."],
    },
    {
      id: 14, label: "Day 14", date: "Thu, Jul 2",
      from: "Bend, OR", to: "Crater Lake / Prospect, OR",
      driveTime: "4-4.5h", miles: "~190 mi", zone: "forest",
      lodgingType: "camp", lodgingName: "Farewell Bend Campground",
      lodgingCost: "~$23-35", lodgingNotes: "Primary USFS campground near Prospect, dog-friendly. Book via recreation.gov.",
      lodgingBackup: "Natural Bridge Campground nearby; Mazama Campground inside Crater Lake NP around $23/night via recreation.gov.",
      route: "Tumalo → Smith Rock at dawn → Bend south → Crater Lake North Entrance",
      routeNotes: "Smith Rock adds a 30-45 minute backtrack. Hit Crater Lake rim at golden hour, roughly 5-7:30 PM.",
      description: "Do Smith Rock at the only dog-safe time in July, then continue to Crater Lake for golden-hour views.",
      stops: ["7:30 AM Smith Rock State Park for a riverside walk or Misery Ridge.", "Crater Lake North Entrance.", "Rim Village promenade.", "Beckie's Cafe in Union Creek."],
      activities: ["Dog-OK Crater Lake options: Lady of the Woods, Godfrey Glen 1-mile loop, Pinnacles Trail, PCT section, Annie Springs Spur, Grayback Rd, Rim Village promenade."],
      food: [{ name: "Beckie's Cafe", note: "Union Creek huckleberry pie." }],
      dogNotes: ["Kye is not allowed at Cleetwood Cove, the lake, or most Crater Lake trails.", "Use only the listed dog-OK paths and paved/rim areas."],
      warnings: ["Keep Kye leashed at Smith Rock and stay alert for rattlesnakes.", "Crater Lake dog access is limited; plan the visit around legal dog areas."],
    },
    {
      id: 15, label: "Day 15", date: "Fri, Jul 3",
      from: "Crater Lake, OR", to: "Lake Almanor, CA",
      driveTime: "5-5.5h", miles: "~245 mi", zone: "forest",
      lodgingType: "camp", lodgingName: "Almanor South Campground",
      lodgingCost: "~$26-30", lodgingNotes: "PROPOSED, NOT YET BOOKED. Confirmed reservable on recreation.gov. West-shore Lake Almanor campground with drinking water, vault toilets, and dogs on leash. Book immediately for July 3.",
      lodgingBackup: "Call Hat Creek Ranger District at 530-336-5521, or book Bigfoot Lodging/private Hipcamp near Almanor.",
      route: "Hwy 62 E → US-97 S → Weed → I-5 S briefly → CA-89 S through McCloud and Burney → Lake Almanor",
      routeNotes: "Gas up at Mt. Shasta City or Burney; stations thin out on CA-89. Optional Lassen Volcanic NP drive adds time.",
      description: "Crater Lake to Lake Almanor via Mt. Shasta, McCloud Falls, and the scenic CA-89 corridor.",
      stops: ["McCloud River Falls off CA-89: dogs on dirt trail; swim at Lower Falls may be possible depending on current, conditions, and signs.", "Mt. Shasta City Park: glacial headwaters of the Sacramento River, paved paths, dog-friendly, fill water jugs."],
      activities: ["Use Mt. Shasta City Park as the cool-down stop before CA-89.", "Walk the Lake Almanor Recreation Trail and let Kye cool off safely in the lake."],
      food: [],
      dogNotes: ["McCloud trail is dog-friendly on leash.", "Check signs and conditions before letting Kye swim."],
      warnings: ["Book Almanor South immediately; do not rely on any FCFS campground Friday July 3.", "Fuel and services thin out on CA-89."],
    },
    {
      id: 16, label: "Day 16", date: "Sat, Jul 4",
      from: "Lake Almanor, CA", to: "Mammoth Lakes Area, CA",
      driveTime: "5.5-6h", miles: "~300 mi", zone: "desert",
      lodgingType: "camp", lodgingName: "Convict Lake Campground",
      lodgingCost: "~$35", lodgingNotes: "PROPOSED, NOT YET BOOKED. Reservable recreation.gov campground at 7,500+ ft with 85 sites, bear lockers, flush toilets, potable water, and leashed dogs. Book now for July 4 weekend.",
      lodgingBackup: "Sherwin Creek or New Shady Rest; Glass Creek FCFS/free or French Camp FCFS south of Mammoth.",
      route: "CA-36 E from Chester/Lake Almanor to Susanville → US-395 S",
      routeNotes: "The longest return day, but the drive is the attraction. Do not camp in Bishop: 4,100 ft and 100-105F in July is dangerous for tent plus dog.",
      description: "A full Highway 395 day through hot springs, Mono Lake, Lee Vining, and Convict Lake.",
      stops: ["Travertine Hot Springs in Bridgeport: free natural hot springs, Sierra views.", "Mono Lake South Tufa: alien calcium-carbonate towers; dogs on leash, not on State Reserve boardwalk.", "Whoa Nellie Deli at Lee Vining Mobil station: fish tacos and Mono Lake views.", "Convict Lake: turquoise alpine lake, granite peaks, flat 2-mile trail, dogs welcome, Kye may swim from shore.", "Little Lakes Valley / Mosquito Flat optional only if you arrive early with energy; do it this afternoon, not tomorrow."],
      activities: ["Stake every guy-line even if calm at 5 PM.", "Watch 395 town speed drops from 70 to 35."],
      food: [{ name: "Whoa Nellie Deli", note: "Fish tacos at the Lee Vining Mobil station with Mono Lake views." }],
      dogNotes: ["Convict Lake is the ultimate dog stop.", "Avoid Bishop camping heat with Kye."],
      warnings: ["No low-demand July 4 Sierra camping; reservations are critical.", "395 speed traps are common in small towns.", "395 wind can arrive fast; stake the tent fully."],
    },
    {
      id: 17, label: "Day 17", date: "Sun, Jul 5",
      from: "Mammoth Lakes Area, CA", to: "Escondido, CA",
      driveTime: "5.5-6.5h", miles: "~330 mi", zone: "desert",
      lodgingType: null, lodgingName: "Home!",
      lodgingCost: "—", lodgingNotes: "Leave by 6-7 AM. Home by 2-5 PM depending on Cajon Pass traffic.",
      lodgingBackup: "—",
      route: "US-395 S → Lone Pine → Red Rock Canyon → CA-14 → I-15/215 → Escondido",
      routeNotes: "Every Tahoe/Mammoth tourist is driving home; earlier departure means less I-15 Cajon Pass traffic.",
      description: "Final Mammoth-to-home push down 395 and through the desert.",
      stops: ["Alabama Hills in Lone Pine: 30-minute sunrise walk among boulders framing Mt. Whitney; dogs welcome.", "Copper Top BBQ in Big Pine: legendary tri-tip.", "Red Rock Canyon quick pullout only: dogs banned from trails, OK in picnic area."],
      activities: ["Leave camp by 6-7 AM.", "Get home by afternoon if traffic behaves."],
      food: [{ name: "Copper Top BBQ", note: "Big Pine tri-tip." }],
      dogNotes: ["Use Alabama Hills for the real morning dog walk.", "Red Rock Canyon is picnic/road only for Kye."],
      warnings: ["Leave early to reduce Cajon Pass traffic and desert heat exposure."],
    },
  ],

  driving: [
    { day: 0, date: "Thu Jun 18", from: "Escondido (7-8 PM)", to: "Ventura", miles: "~150", time: "2.75-3.5h", long: false },
    { day: 1, date: "Fri Jun 19", from: "Ventura", to: "Morro Bay", miles: "~150", time: "2.5-3h", long: false },
    { day: 2, date: "Sat Jun 20", from: "Morro Bay", to: "Monterey via Big Sur", miles: "~145", time: "3.5-4.5h", long: false },
    { day: 3, date: "Sun Jun 21", from: "Monterey/Carmel", to: "—", miles: "—", time: "Minimal", long: false },
    { day: 4, date: "Mon Jun 22", from: "Monterey", to: "San Jose", miles: "~75-120", time: "2-3h", long: false },
    { day: 5, date: "Tue Jun 23", from: "San Jose", to: "Van Damme / Mendocino", miles: "~200", time: "5.5-6.5h", long: true, flagNote: "Friend-plan long coast day" },
    { day: 6, date: "Wed Jun 24", from: "Van Damme / Mendocino", to: "Burlington Camp, Humboldt Redwoods", miles: "~100", time: "2.5h direct; 4-5h with stops", long: false },
    { day: 7, date: "Thu Jun 25", from: "Burlington Camp", to: "Humbug Mountain State Park", miles: "~185", time: "3.5-4h", long: false },
    { day: 8, date: "Fri Jun 26", from: "Humbug Mountain", to: "Barview Jetty / Rockaway Beach", miles: "~230", time: "5.5-6h driving; 7.5h+ total", long: true, flagNote: "Long scenic US-101 day" },
    { day: 9, date: "Sat Jun 27", from: "Barview Jetty", to: "Millersylvania / Olympia", miles: "~145", time: "3-3.5h", long: false, flagNote: "Cannon Beach + Astoria stops" },
    { day: 10, date: "Sun Jun 28", from: "Millersylvania / Olympia", to: "Seattle", miles: "~77", time: "1.75-2h", long: false },
    { day: 11, date: "Mon Jun 29", from: "Seattle (work)", to: "—", miles: "—", time: "Minimal", long: false },
    { day: 12, date: "Tue Jun 30", from: "Seattle (1-2 PM)", to: "Portland Airbnb", miles: "~175", time: "3-3.5h", long: false },
    { day: 13, date: "Wed Jul 1", from: "Portland", to: "Bend via Mt. Hood", miles: "~160", time: "3-3.5h direct; 4.5-5.5h with stops", long: true, flagNote: "Trillium Lake + lunch" },
    { day: 14, date: "Thu Jul 2", from: "Bend via Smith Rock AM", to: "Crater Lake", miles: "~190", time: "4-4.5h", long: false },
    { day: 15, date: "Fri Jul 3", from: "Crater Lake", to: "Lake Almanor via Shasta/McCloud", miles: "~245", time: "5-5.5h", long: true, flagNote: "Holiday weekend reservation critical" },
    { day: 16, date: "Sat Jul 4", from: "Lake Almanor", to: "Mammoth via 395", miles: "~300", time: "5.5-6h", long: true, flagNote: "Longest return day" },
    { day: 17, date: "Sun Jul 5", from: "Mammoth", to: "Escondido", miles: "~330", time: "5.5-6.5h", long: true, flagNote: "Leave by 6-7 AM" },
  ],

  budget: {
    categories: [
      { name: "Lodging", color: "#2a7ea8", items: [
        { label: "12 camp nights (5 booked total $235.75)", amount: 455 },
        { label: "Motels: Ventura and San Jose", amount: 170 },
        { label: "Airbnb: 2 Seattle + 1 Portland", amount: 540 },
      ]},
      { name: "Transportation", color: "#8a6540", items: [
        { label: "Gas (~3,700 mi at 25 mpg, $4.50/gal)", amount: 680 },
      ]},
      { name: "Food", color: "#c8832a", items: [
        { label: "Food (~$50/day x 18 days for 2)", amount: 900 },
      ]},
      { name: "Dog", color: "#8b4f3c", items: [
        { label: "Dog fees: 3 Airbnb pet fees + some camp fees", amount: 90 },
      ]},
      { name: "Misc", color: "#6b6060", items: [
        { label: "Firewood, supplies, parking", amount: 150 },
        { label: "Contingency", amount: 200 },
      ]},
    ]
  },

  bookings: [
    { p: 1, what: "Morro Bay SP Upper Section, Site 123 (Jun 19)", how: "ReserveCalifornia / Web Bookings", urgency: "critical", notes: "BOOKED: confirmation #29558779, $43.25 paid", status: "booked" },
    { p: 2, what: "Van Damme SP Upper Loop, Site 033 (Jun 23)", how: "ReserveCalifornia / Web Bookings", urgency: "critical", notes: "BOOKED: confirmation #29557920, $53.25 paid", status: "booked" },
    { p: 3, what: "Humboldt Redwoods SP Burlington Camp Tent Site 004Bu (Jun 24)", how: "ReserveCalifornia / Web Bookings", urgency: "critical", notes: "BOOKED: confirmation #29559795, $43.25 paid", status: "booked" },
    { p: 4, what: "Humbug Mountain State Park Tent Site 54 (Jun 25)", how: "Oregon State Parks / ReserveAmerica", urgency: "critical", notes: "BOOKED: reservation #2-38213261, $50.00 paid", status: "booked" },
    { p: 5, what: "Barview Jetty County Campground Blue Tent Site C2 (Jun 26)", how: "Tillamook County Parks / Campspot", urgency: "critical", notes: "BOOKED: confirmation #R00000007782, $46.00 paid", status: "booked" },
    { p: 6, what: "Millersylvania State Park (Jun 27)", how: "washington.goingtocamp.com", urgency: "critical", notes: "Book immediately", status: "pending" },
    { p: 7, what: "Convict Lake CG (Jul 4)", how: "recreation.gov", urgency: "critical", notes: "July 4 weekend", status: "pending" },
    { p: 8, what: "Almanor South CG, Lake Almanor (Jul 3)", how: "recreation.gov", urgency: "critical", notes: "Confirmed reservable; do not rely on FCFS", status: "pending" },
    { p: 9, what: "Farewell Bend or Natural Bridge CG (Jul 2)", how: "recreation.gov / USFS", urgency: "very-high", notes: "Crater Lake area", status: "pending" },
    { p: 10, what: "Tumalo State Park (Jul 1)", how: "oregonstateparks.reserveamerica.com", urgency: "very-high", notes: "Bend area", status: "pending" },
    { p: 11, what: "Seattle Airbnb (Jun 28-29, 2 nights)", how: "Airbnb", urgency: "high", notes: "Ballard, pet-friendly, fenced yard", status: "pending" },
    { p: "11b", what: "Portland Airbnb (Jun 30, 1 night)", how: "Airbnb", urgency: "high", notes: "Pet-friendly SE Portland/Hawthorne or N/Mississippi", status: "pending" },
    { p: 12, what: "Laguna Seca backup (Jun 20-21)", how: "Call 888-588-2267", urgency: "high", notes: "Ask about track events for full weekend", status: "pending" },
    { p: 13, what: "Motel 6 Ventura Beach (Jun 18)", how: "motel6.com", urgency: "moderate", notes: "Night 0", status: "pending" },
    { p: 14, what: "Motel 6 San Jose South (Jun 22)", how: "motel6.com", urgency: "moderate", notes: "Bay Area night", status: "pending" },
    { p: "—", what: "Veterans Memorial Park, Monterey", how: "FCFS only", urgency: "high", notes: "Arrive Sat Jun 20 by noon", status: "pending" },
  ],

  dogRules: [
    { location: "Morro Bay SP, CA", allowed: ["Campground on leash", "Developed areas and waterfront walks where posted dog rules allow"], notAllowed: ["Signed wildlife-sensitive areas", "Most dirt state park trails unless specifically posted dog-friendly"], notes: "Booked site 123 for Jun 19." },
    { location: "Pismo Beach, CA", allowed: ["Beach walks on leash during an optional stop"], notAllowed: ["Oso Flaco", "Dunes Preserve"], notes: "Pismo is now an optional stop, not the overnight camp." },
    { location: "Van Damme SP, CA", allowed: ["Campground on leash", "Developed areas"], notAllowed: ["Restricted state park trails"], notes: "Booked Upper Loop site 033 for Jun 23." },
    { location: "Carmel Beach, CA", allowed: ["OFF-LEASH under voice control within 25 ft", "Carmel village patios"], notAllowed: ["Scenic Pathway"], notes: "One of the biggest Kye highlights." },
    { location: "Seattle Beaches", allowed: ["Magnuson Park off-leash area only", "Ballard Locks and Gas Works on leash"], notAllowed: ["Alki and other regular Seattle beaches"], notes: "Seattle beach rules are stricter than Oregon coast rules." },
    { location: "Humboldt Redwoods", allowed: ["Campgrounds", "Paved/developed areas", "Avenue of the Giants pullouts", "Mattole Road shoulder"], notAllowed: ["All dirt trails"], notes: "Cal Barrel Road and Howland Hill Road are farther north on Day 7, not Humboldt Redwoods." },
    { location: "Redwood road detours", allowed: ["Cal Barrel Road and Howland Hill Road shoulders on leash"], notAllowed: ["Most park trails"], notes: "Use legal road walks while passing through on Day 7." },
    { location: "Oregon Coast Beaches", allowed: ["Voice-control off-leash access on wet packed sand where posted rules allow"], notAllowed: ["Dry sand behind yellow Snowy Plover nesting signs from Mar 15-Sep 15"], notes: "Obey every posted nesting restriction." },
    { location: "Humbug Mountain / Barview Jetty", allowed: ["Campgrounds on leash", "Beach access where posted rules allow"], notAllowed: ["Snowy Plover restricted dry-sand areas"], notes: "Humbug Mountain tent site 54 and Barview Blue Tent Site C2 are booked. Barview can be very windy; secure the tent heavily." },
    { location: "Millersylvania State Park", allowed: ["Campground and trails on leash no longer than 8 ft", "Quiet shoreline water access on leash"], notAllowed: ["Two designated human swimming beaches"], notes: "Kye must remain leashed even in the water." },
    { location: "Crater Lake NP", allowed: ["Rim Village promenade", "Lady of the Woods", "Godfrey Glen", "PCT section", "Pinnacles", "Annie Springs Spur", "Grayback Rd"], notAllowed: ["Cleetwood Cove", "The lake", "Most trails"], notes: "Use only the specific dog-OK areas." },
    { location: "Smith Rock, OR", allowed: ["All trails on leash"], notAllowed: ["Off-leash hiking"], notes: "Rattlesnake alert: stay on trail." },
    { location: "Trillium Lake, OR", allowed: ["Loop trail on leash", "Lake wading and swimming from shore on leash"], notAllowed: ["Off-leash hiking"], notes: "Top Mt. Hood dog stop; use Frog Lake if crowded." },
    { location: "McCloud River Falls", allowed: ["Trail on leash", "Possible swim at Lower Falls if safe and posted signs allow"], notAllowed: ["Unsafe current or restricted swim areas"], notes: "Check signs and conditions before Kye swims." },
    { location: "Convict Lake", allowed: ["Trail on leash", "Shore access", "Possible swim from shore"], notAllowed: ["Disturbing wildlife"], notes: "The plan's ultimate dog stop." },
    { location: "Mono Lake South Tufa", allowed: ["Tufa area on leash"], notAllowed: ["State Reserve boardwalk"], notes: "Keep to dog-legal sections." },
    { location: "Red Rock Canyon SP", allowed: ["Campground, picnic areas, roads"], notAllowed: ["Trails"], notes: "Day 17 is quick pullout only." },
    { location: "Alabama Hills", allowed: ["BLM dog-friendly walking"], notAllowed: ["Unsafe heat exposure"], notes: "Best final-day sunrise dog walk." },
  ],

  food: [
    { name: "Splash Cafe", loc: "Pismo Beach, CA", day: 1, type: "seafood", desc: "Optional clam chowder bread bowl stop en route to Morro Bay.", dog: false },
    { name: "Princess Seafood Market", loc: "Fort Bragg, CA", day: 5, type: "seafood", desc: "Crab rolls on the dock.", dog: true },
    { name: "Eel River Brewing", loc: "Fortuna, CA", day: 6, type: "brewery", desc: "Massive dog patio after the redwoods.", dog: true },
    { name: "Bowpicker Fish & Chips", loc: "Astoria, OR", day: 9, type: "seafood", desc: "Fish and chips served from a boat before crossing into Washington.", dog: true },
    { name: "Stoup Brewing / Reuben's Brews", loc: "Ballard, Seattle", day: 10, type: "brewery", desc: "Dog-friendly taprooms for the Seattle arrival evening.", dog: true },
    { name: "Norm's Eatery & Alehouse", loc: "Fremont, Seattle", day: 11, type: "pub", desc: "Dogs allowed inside, cool floor, dedicated dog menu.", dog: true },
    { name: "Hawthorne Asylum / Lucky Labrador / Baerlic", loc: "Portland, OR", day: 12, type: "brewery", desc: "Dog-friendly Portland food carts and breweries.", dog: true },
    { name: "Mt. Hood Brewing", loc: "Government Camp, OR", day: 13, type: "brewery", desc: "Patio lunch with mountain views.", dog: true },
    { name: "Crux Fermentation Project", loc: "Bend, OR", day: 13, type: "brewery", desc: "Beer, grassy sunset lawn, Cascade mountain views, dogs welcome.", dog: true },
    { name: "The Bite", loc: "Tumalo, OR", day: 13, type: "pub", desc: "Low-stress dog-friendly food-truck pod with lawn and central taphouse.", dog: true },
    { name: "Beckie's Cafe", loc: "Union Creek, OR", day: 14, type: "cafe", desc: "Huckleberry pie near Crater Lake.", dog: false },
    { name: "Whoa Nellie Deli", loc: "Lee Vining, CA", day: 16, type: "diner", desc: "Fish tacos at the Mobil station with Mono Lake views.", dog: true },
    { name: "Copper Top BBQ", loc: "Big Pine, CA", day: 17, type: "restaurant", desc: "Legendary tri-tip on the final 395 drive.", dog: true },
  ],

  packing: [
    { cat: "🐾 Dog", items: ["6-foot leash, no retractables", "Collapsible water bowl + extra water jugs", "Dog booties (Ruffwear Grip Trex)", "Cooling vest (Ruffwear Swamp Cooler)", "Tweezers + headlamp for nightly foxtail checks", "Poop bags, dog first aid kit", "Blanket/bed for tent", "Vaccination records + ID tags", "Photo of Kye on phone", "Fresh flea/tick preventative dose this week"] },
    { cat: "🏕 Camping", items: ["Tent with removable rainfly", "Aluminet shade cloth", "Bear canister or plan for bear lockers", "Warm layers for coast/mountains + light clothing for valleys", "Rain jacket for Oregon/Washington", "Battery-powered fan", "Headlamp", "Portable power bank for non-electric camp nights", "Firewood money ($8-12/bundle, do not transport across state lines)", "3 extra gallons emergency water", "Baby oil + rag for beach tar removal"] },
    { cat: "📱 Apps", items: ["Watch Duty for wildfire checks", "Caltrans QuickMap for road closures", "Campflare or Campnab for cancellation alerts", "iOverlander + Campendium for dispersed camping GPS"] },
    { cat: "💻 Work", items: ["Laptop + charger", "Portable wifi hotspot as optional backup"] },
  ],

  todos: [
    { cat: "Book Now", items: ["BOOKED: Morro Bay SP Upper Section site 123 (Jun 19), confirmation #29558779", "BOOKED: Van Damme SP Upper Loop site 033 (Jun 23), confirmation #29557920", "BOOKED: Humboldt Redwoods SP Burlington Camp tent site 004Bu (Jun 24), confirmation #29559795", "BOOKED: Humbug Mountain State Park tent site 54 (Jun 25), reservation #2-38213261", "BOOKED: Barview Jetty County Campground Blue Tent Site C2 (Jun 26), confirmation #R00000007782", "Millersylvania State Park (Jun 27) via washington.goingtocamp.com", "Convict Lake CG (Jul 4) via recreation.gov", "Almanor South CG, Lake Almanor (Jul 3) via recreation.gov", "Farewell Bend or Natural Bridge CG (Jul 2) via recreation.gov", "Tumalo State Park (Jul 1) via oregonstateparks.reserveamerica.com", "Seattle Airbnb: 2 nights Jun 28-29, Ballard, pet-friendly, fenced yard", "Portland Airbnb: 1 night Jun 30, pet-friendly SE Portland/Hawthorne or N/Mississippi", "Call Laguna Seca (888-588-2267): Jun 20-21 tent site, dog policy, track events", "Motel 6 Ventura Beach (Jun 18)", "Motel 6 San Jose South (Jun 22)"] },
    { cat: "Gear & Car", items: ["Oil change", "Tire check including spare", "AC and coolant systems topped off", "Buy baby oil, extra water jugs, power bank", "Bear canister check / confirm campground bear lockers"] },
    { cat: "Dog Prep", items: ["Fresh flea/tick preventative dose this week", "Bootie training at home (let Kye do the moonwalk)", "Confirm vaccination records are current"] },
  ],
};
